[package]
name = "spirq"
version = "0.1.0"
authors = ["PENGUINLIONG <admin@penguinliong.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
log = "0.4.8"
env_logger = "0.7.1"
bytes = "0.4.12"
byteorder = "1.3.2"

[[example]]
name = "query"
path = "examples/query/main.rs"
